
package com.jdm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @param vpBatch4Xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MyCzzxWeb", action = "http://tempuri.org/MyCzzxWeb")
    @WebResult(name = "MyCzzxWebResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MyCzzxWeb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb")
    @ResponseWrapper(localName = "MyCzzxWebResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWebResponse")
    public String myCzzxWeb(
        @WebParam(name = "vpBatch4Xml", targetNamespace = "http://tempuri.org/")
        String vpBatch4Xml);

    /**
     * 
     * @param vpPwd
     * @param vpCodeId
     * @param vpSql
     * @param vpMyType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MyCzzxWeb4SqlSel4His", action = "http://tempuri.org/MyCzzxWeb4SqlSel4His")
    @WebResult(name = "MyCzzxWeb4SqlSel4HisResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MyCzzxWeb4SqlSel4His", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlSel4His")
    @ResponseWrapper(localName = "MyCzzxWeb4SqlSel4HisResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlSel4HisResponse")
    public String myCzzxWeb4SqlSel4His(
        @WebParam(name = "vpSql", targetNamespace = "http://tempuri.org/")
        String vpSql,
        @WebParam(name = "vpCodeId", targetNamespace = "http://tempuri.org/")
        String vpCodeId,
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd,
        @WebParam(name = "vpMyType", targetNamespace = "http://tempuri.org/")
        String vpMyType);

    /**
     * 
     * @param vpPwd
     * @param vpCodeId
     * @param vpSql
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MyCzzxWeb4SqlSel4His4DanYiZhi", action = "http://tempuri.org/MyCzzxWeb4SqlSel4His4DanYiZhi")
    @WebResult(name = "MyCzzxWeb4SqlSel4His4DanYiZhiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MyCzzxWeb4SqlSel4His4DanYiZhi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlSel4His4DanYiZhi")
    @ResponseWrapper(localName = "MyCzzxWeb4SqlSel4His4DanYiZhiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlSel4His4DanYiZhiResponse")
    public String myCzzxWeb4SqlSel4His4DanYiZhi(
        @WebParam(name = "vpSql", targetNamespace = "http://tempuri.org/")
        String vpSql,
        @WebParam(name = "vpCodeId", targetNamespace = "http://tempuri.org/")
        String vpCodeId,
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd);

    /**
     * 
     * @param vpSql9
     * @param vpSql8
     * @param vpSql5
     * @param vpSql4
     * @param vpSql7
     * @param vpSql6
     * @param vpSql1
     * @param vpSql11
     * @param vpSql12
     * @param vpSql3
     * @param vpSql13
     * @param vpSql2
     * @param vpSql14
     * @param vpSql20
     * @param vpSql10
     * @param vpSql19
     * @param vpCodeIdAndPwd
     * @param vpSql15
     * @param vpSql16
     * @param vpSql17
     * @param vpSql18
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MyCzzxWeb4SqlExe4His", action = "http://tempuri.org/MyCzzxWeb4SqlExe4His")
    @WebResult(name = "MyCzzxWeb4SqlExe4HisResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MyCzzxWeb4SqlExe4His", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlExe4His")
    @ResponseWrapper(localName = "MyCzzxWeb4SqlExe4HisResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlExe4HisResponse")
    public String myCzzxWeb4SqlExe4His(
        @WebParam(name = "vpCodeIdAndPwd", targetNamespace = "http://tempuri.org/")
        String vpCodeIdAndPwd,
        @WebParam(name = "vpSql1", targetNamespace = "http://tempuri.org/")
        String vpSql1,
        @WebParam(name = "vpSql2", targetNamespace = "http://tempuri.org/")
        String vpSql2,
        @WebParam(name = "vpSql3", targetNamespace = "http://tempuri.org/")
        String vpSql3,
        @WebParam(name = "vpSql4", targetNamespace = "http://tempuri.org/")
        String vpSql4,
        @WebParam(name = "vpSql5", targetNamespace = "http://tempuri.org/")
        String vpSql5,
        @WebParam(name = "vpSql6", targetNamespace = "http://tempuri.org/")
        String vpSql6,
        @WebParam(name = "vpSql7", targetNamespace = "http://tempuri.org/")
        String vpSql7,
        @WebParam(name = "vpSql8", targetNamespace = "http://tempuri.org/")
        String vpSql8,
        @WebParam(name = "vpSql9", targetNamespace = "http://tempuri.org/")
        String vpSql9,
        @WebParam(name = "vpSql10", targetNamespace = "http://tempuri.org/")
        String vpSql10,
        @WebParam(name = "vpSql11", targetNamespace = "http://tempuri.org/")
        String vpSql11,
        @WebParam(name = "vpSql12", targetNamespace = "http://tempuri.org/")
        String vpSql12,
        @WebParam(name = "vpSql13", targetNamespace = "http://tempuri.org/")
        String vpSql13,
        @WebParam(name = "vpSql14", targetNamespace = "http://tempuri.org/")
        String vpSql14,
        @WebParam(name = "vpSql15", targetNamespace = "http://tempuri.org/")
        String vpSql15,
        @WebParam(name = "vpSql16", targetNamespace = "http://tempuri.org/")
        String vpSql16,
        @WebParam(name = "vpSql17", targetNamespace = "http://tempuri.org/")
        String vpSql17,
        @WebParam(name = "vpSql18", targetNamespace = "http://tempuri.org/")
        String vpSql18,
        @WebParam(name = "vpSql19", targetNamespace = "http://tempuri.org/")
        String vpSql19,
        @WebParam(name = "vpSql20", targetNamespace = "http://tempuri.org/")
        String vpSql20);

    /**
     * 
     * @param vpIns
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MyCzzxCCB", action = "http://tempuri.org/MyCzzxCCB")
    @WebResult(name = "MyCzzxCCBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MyCzzxCCB", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxCCB")
    @ResponseWrapper(localName = "MyCzzxCCBResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxCCBResponse")
    public String myCzzxCCB(
        @WebParam(name = "vpIns", targetNamespace = "http://tempuri.org/")
        String vpIns);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDoctors", action = "http://tempuri.org/GetDoctors")
    @WebResult(name = "GetDoctorsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDoctors", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDoctors")
    @ResponseWrapper(localName = "GetDoctorsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDoctorsResponse")
    public String getDoctors();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetQueueTypes", action = "http://tempuri.org/GetQueueTypes")
    @WebResult(name = "GetQueueTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueueTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQueueTypes")
    @ResponseWrapper(localName = "GetQueueTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQueueTypesResponse")
    public String getQueueTypes();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDoctorToQueuetypes", action = "http://tempuri.org/GetDoctorToQueuetypes")
    @WebResult(name = "GetDoctorToQueuetypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDoctorToQueuetypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDoctorToQueuetypes")
    @ResponseWrapper(localName = "GetDoctorToQueuetypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDoctorToQueuetypesResponse")
    public String getDoctorToQueuetypes();

    /**
     * 
     * @param vpId4Card
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPatientQueue", action = "http://tempuri.org/GetPatientQueue")
    @WebResult(name = "GetPatientQueueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPatientQueue", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPatientQueue")
    @ResponseWrapper(localName = "GetPatientQueueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPatientQueueResponse")
    public String getPatientQueue(
        @WebParam(name = "vpId4Card", targetNamespace = "http://tempuri.org/")
        String vpId4Card);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MedicationSync", action = "http://tempuri.org/MedicationSync")
    @WebResult(name = "MedicationSyncResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MedicationSync", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MedicationSync")
    @ResponseWrapper(localName = "MedicationSyncResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MedicationSyncResponse")
    public String medicationSync();

    /**
     * 
     * @param vpPwd
     * @param vpMyType
     * @param vpSqkGoodsId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MedicationSyncHISRemove", action = "http://tempuri.org/MedicationSyncHISRemove")
    @WebResult(name = "MedicationSyncHISRemoveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MedicationSyncHISRemove", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MedicationSyncHISRemove")
    @ResponseWrapper(localName = "MedicationSyncHISRemoveResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MedicationSyncHISRemoveResponse")
    public String medicationSyncHISRemove(
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd,
        @WebParam(name = "vpMyType", targetNamespace = "http://tempuri.org/")
        String vpMyType,
        @WebParam(name = "vpSqkGoodsId", targetNamespace = "http://tempuri.org/")
        String vpSqkGoodsId);

    /**
     * 
     * @param vpWindowNo
     * @param vpStatus
     * @param vpPrescriptionIDList
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TaskStatusUpdate", action = "http://tempuri.org/TaskStatusUpdate")
    @WebResult(name = "TaskStatusUpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TaskStatusUpdate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TaskStatusUpdate")
    @ResponseWrapper(localName = "TaskStatusUpdateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TaskStatusUpdateResponse")
    public String taskStatusUpdate(
        @WebParam(name = "vpPrescriptionIDList", targetNamespace = "http://tempuri.org/")
        String vpPrescriptionIDList,
        @WebParam(name = "vpWindowNo", targetNamespace = "http://tempuri.org/")
        String vpWindowNo,
        @WebParam(name = "vpStatus", targetNamespace = "http://tempuri.org/")
        String vpStatus);

    /**
     * 
     * @param vpBatch4Xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebMzDoc", action = "http://tempuri.org/WebMzDoc")
    @WebResult(name = "WebMzDocResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WebMzDoc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WebMzDoc")
    @ResponseWrapper(localName = "WebMzDocResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WebMzDocResponse")
    public String webMzDoc(
        @WebParam(name = "vpBatch4Xml", targetNamespace = "http://tempuri.org/")
        String vpBatch4Xml);

    /**
     * 
     * @param vpBatch4Xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebZyNur", action = "http://tempuri.org/WebZyNur")
    @WebResult(name = "WebZyNurResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WebZyNur", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WebZyNur")
    @ResponseWrapper(localName = "WebZyNurResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WebZyNurResponse")
    public String webZyNur(
        @WebParam(name = "vpBatch4Xml", targetNamespace = "http://tempuri.org/")
        String vpBatch4Xml);

    /**
     * 
     * @param vpMyDate4Yw
     * @param vpMyBirthday
     * @param vpkSiteId
     * @param vpSex
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMzGhAgeSexCheckNew", action = "http://tempuri.org/GetMzGhAgeSexCheckNew")
    @WebResult(name = "GetMzGhAgeSexCheckNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMzGhAgeSexCheckNew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMzGhAgeSexCheckNew")
    @ResponseWrapper(localName = "GetMzGhAgeSexCheckNewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMzGhAgeSexCheckNewResponse")
    public String getMzGhAgeSexCheckNew(
        @WebParam(name = "vpkSiteId", targetNamespace = "http://tempuri.org/")
        String vpkSiteId,
        @WebParam(name = "vpSex", targetNamespace = "http://tempuri.org/")
        String vpSex,
        @WebParam(name = "vpMyBirthday", targetNamespace = "http://tempuri.org/")
        String vpMyBirthday,
        @WebParam(name = "vpMyDate4Yw", targetNamespace = "http://tempuri.org/")
        String vpMyDate4Yw);

    /**
     * 
     * @param vpPwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetMzGhAgeSexCheck", action = "http://tempuri.org/SetMzGhAgeSexCheck")
    @WebResult(name = "SetMzGhAgeSexCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetMzGhAgeSexCheck", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetMzGhAgeSexCheck")
    @ResponseWrapper(localName = "SetMzGhAgeSexCheckResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetMzGhAgeSexCheckResponse")
    public String setMzGhAgeSexCheck(
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd);

    /**
     * 
     * @param vpContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EncodeBase64", action = "http://tempuri.org/EncodeBase64")
    @WebResult(name = "EncodeBase64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EncodeBase64", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EncodeBase64")
    @ResponseWrapper(localName = "EncodeBase64Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EncodeBase64Response")
    public String encodeBase64(
        @WebParam(name = "vpContent", targetNamespace = "http://tempuri.org/")
        String vpContent);

    /**
     * 
     * @param vpContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DecodeBase64", action = "http://tempuri.org/DecodeBase64")
    @WebResult(name = "DecodeBase64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DecodeBase64", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DecodeBase64")
    @ResponseWrapper(localName = "DecodeBase64Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DecodeBase64Response")
    public String decodeBase64(
        @WebParam(name = "vpContent", targetNamespace = "http://tempuri.org/")
        String vpContent);

    /**
     * 
     * @param vpContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMD5", action = "http://tempuri.org/GetMD5")
    @WebResult(name = "GetMD5Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMD5", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMD5")
    @ResponseWrapper(localName = "GetMD5Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMD5Response")
    public String getMD5(
        @WebParam(name = "vpContent", targetNamespace = "http://tempuri.org/")
        String vpContent);

    /**
     * 
     * @param vpPwd
     * @param vpUserId
     * @param vpMyInfoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MyCzzxWeb4SqlSel4His4GeneFromDb", action = "http://tempuri.org/MyCzzxWeb4SqlSel4His4GeneFromDb")
    @WebResult(name = "MyCzzxWeb4SqlSel4His4GeneFromDbResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MyCzzxWeb4SqlSel4His4GeneFromDb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlSel4His4GeneFromDb")
    @ResponseWrapper(localName = "MyCzzxWeb4SqlSel4His4GeneFromDbResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MyCzzxWeb4SqlSel4His4GeneFromDbResponse")
    public String myCzzxWeb4SqlSel4His4GeneFromDb(
        @WebParam(name = "vpUserId", targetNamespace = "http://tempuri.org/")
        String vpUserId,
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd,
        @WebParam(name = "vpMyInfoXML", targetNamespace = "http://tempuri.org/")
        String vpMyInfoXML);

    /**
     * 
     * @param vpPwd
     * @param vpMyInfo
     * @param vpTeleList
     * @param vpUserId
     * @param vpsign
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "XxzyyyDuanXinHuLianWangGet", action = "http://tempuri.org/XxzyyyDuanXinHuLianWangGet")
    @WebResult(name = "XxzyyyDuanXinHuLianWangGetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "XxzyyyDuanXinHuLianWangGet", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XxzyyyDuanXinHuLianWangGet")
    @ResponseWrapper(localName = "XxzyyyDuanXinHuLianWangGetResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XxzyyyDuanXinHuLianWangGetResponse")
    public String xxzyyyDuanXinHuLianWangGet(
        @WebParam(name = "vpUserId", targetNamespace = "http://tempuri.org/")
        String vpUserId,
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd,
        @WebParam(name = "vpTeleList", targetNamespace = "http://tempuri.org/")
        String vpTeleList,
        @WebParam(name = "vpMyInfo", targetNamespace = "http://tempuri.org/")
        String vpMyInfo,
        @WebParam(name = "vpsign", targetNamespace = "http://tempuri.org/")
        String vpsign);

    /**
     * 
     * @param vpPwd
     * @param vpMyInfo
     * @param vpTeleList
     * @param vpUserId
     * @param vpsign
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "XxzyyyDuanXinHuLianWangPost", action = "http://tempuri.org/XxzyyyDuanXinHuLianWangPost")
    @WebResult(name = "XxzyyyDuanXinHuLianWangPostResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "XxzyyyDuanXinHuLianWangPost", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XxzyyyDuanXinHuLianWangPost")
    @ResponseWrapper(localName = "XxzyyyDuanXinHuLianWangPostResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XxzyyyDuanXinHuLianWangPostResponse")
    public String xxzyyyDuanXinHuLianWangPost(
        @WebParam(name = "vpUserId", targetNamespace = "http://tempuri.org/")
        String vpUserId,
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd,
        @WebParam(name = "vpTeleList", targetNamespace = "http://tempuri.org/")
        String vpTeleList,
        @WebParam(name = "vpMyInfo", targetNamespace = "http://tempuri.org/")
        String vpMyInfo,
        @WebParam(name = "vpsign", targetNamespace = "http://tempuri.org/")
        String vpsign);

    /**
     * 
     * @param vpPwd
     * @param vpMyInfo
     * @param vpUserId
     * @param vpIsPost
     * @param vpbasOperId
     * @param vpsign
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "XxzyyyDuanXinHuLianWang", action = "http://tempuri.org/XxzyyyDuanXinHuLianWang")
    @WebResult(name = "XxzyyyDuanXinHuLianWangResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "XxzyyyDuanXinHuLianWang", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XxzyyyDuanXinHuLianWang")
    @ResponseWrapper(localName = "XxzyyyDuanXinHuLianWangResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.XxzyyyDuanXinHuLianWangResponse")
    public String xxzyyyDuanXinHuLianWang(
        @WebParam(name = "vpUserId", targetNamespace = "http://tempuri.org/")
        String vpUserId,
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd,
        @WebParam(name = "vpbasOperId", targetNamespace = "http://tempuri.org/")
        String vpbasOperId,
        @WebParam(name = "vpMyInfo", targetNamespace = "http://tempuri.org/")
        String vpMyInfo,
        @WebParam(name = "vpsign", targetNamespace = "http://tempuri.org/")
        String vpsign,
        @WebParam(name = "vpIsPost", targetNamespace = "http://tempuri.org/")
        String vpIsPost);

    /**
     * 
     * @param vpPwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetIsDebug", action = "http://tempuri.org/SetIsDebug")
    @WebResult(name = "SetIsDebugResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetIsDebug", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetIsDebug")
    @ResponseWrapper(localName = "SetIsDebugResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetIsDebugResponse")
    public String setIsDebug(
        @WebParam(name = "vpPwd", targetNamespace = "http://tempuri.org/")
        String vpPwd);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIsDebug", action = "http://tempuri.org/GetIsDebug")
    @WebResult(name = "GetIsDebugResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIsDebug", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsDebug")
    @ResponseWrapper(localName = "GetIsDebugResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsDebugResponse")
    public String getIsDebug();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://tempuri.org/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMyDateWebServer", action = "http://tempuri.org/GetMyDateWebServer")
    @WebResult(name = "GetMyDateWebServerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMyDateWebServer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMyDateWebServer")
    @ResponseWrapper(localName = "GetMyDateWebServerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMyDateWebServerResponse")
    public String getMyDateWebServer();

}
